name: shell commands

on: [push]

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: simple js run-github-actions
        id: greet 
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: yuval
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"