name: shell commands
# test
on: 
  push:
  pull_request:
    types: [closed, assigned]

env:
  ENV: all jobs can see

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    env:
      JOB_ENV: env numbrt 2
    steps:
      - name: list files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1
      - name: list files after
        run: |
          pwd
          ls -a
      - name: simple js run-github-actions
        id: greet 
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: yuval
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: print env variables
        run: |
          echo "first var": ${ENV}
          echo "second var": ${JOB_ENV}