name: matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: log node node-version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: log node node-version
        run: node -v